### ISSUE TITLE
Dock manager styling sample improvements

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-wc-examples#118]
The title in the Global Electricity pie chart doesn't fit in the screen. We should make it shorter.

![image](https://user-images.githubusercontent.com/1472513/138697474-02418739-01ba-43e7-aa97-cd965338ff3e.png)

Also the sample should define at least one other layout for smaller screen size breakpoint.

![image](https://user-images.githubusercontent.com/1472513/138697809-134fcb95-7066-4c3d-8669-686a02f8e4b7.png)

**Comment by DiyanDimitrov** [comment]
> Also the sample should define at least one other layout for smaller screen size breakpoint.

@kdinev, This could not be achieved using CSS only like a flexbox. The dockmanager component is desktop oriented and I am not sure if we should target such small screens. However we could add a resize observer and change the dockmanager layout object (combine panes in tab groups or unpin panes) based on the available width. Also I am not sure if this should be part of the styling sample. Please let me know what you think.
