### ISSUE TITLE
Correct Marker Position

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-wc-examples#208]
In the composite-chart sample, last value marker should be moved to left side such that is is in center of a column. 
https://github.com/IgniteUI/igniteui-wc-examples/tree/vnext/samples/charts/data-chart/composite-chart

NOTE this issue also occurs in Blazor and React sample

![image](https://user-images.githubusercontent.com/11665978/151043614-baa9089b-91a3-4e69-b7a5-8c6648ab3404.png)

**Comment by mddifilippo89** [comment]
Fyi, it's an issue specific to the iframe/codeviewer not with the sample loaded normally. It looks like the callouts is adjusting according to the overall size of the chart. Not a sample bug.

**Comment by HUSSAR-mtrela** [comment]
@mddifilippo89  Try removing 2-3 data items to make more horizontal space for categories/callouts
