### ISSUE TITLE
Expansion-Panel samples do not compile 

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-wc-examples#279]
Expansion-Panel samples throw errors:

 [1m[33mWARNING in ./samples/layouts/expansion-panel/styling/index.ts 4:210-236
 "export 'IgcExpansionPanelComponent' was not found in 'igniteui-webcomponents'

 [1m[33mWARNING in ./samples/layouts/expansion-panel/properties-and-events/index.ts 4:203-229
 "export 'IgcExpansionPanelComponent' was not found in 'igniteui-webcomponents'

 [1m[33mWARNING in ./samples/layouts/expansion-panel/component-customization/index.ts 4:216-242
 "export 'IgcExpansionPanelComponent' was not found in 'igniteui-webcomponents'
 
 [1m[33mWARNING in ./samples/layouts/expansion-panel/usage/index.ts 4:189-215
 "export 'IgcExpansionPanelComponent' was not found in 'igniteui-webcomponents'

**Comment by MonikaKirkova** [comment]
After updating the version of the igniteui-webcomponents the issue is not reproduced
