### ISSUE TITLE
Inconsistent sizes of circular-progress-indicator

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-wc-examples#299]
IG component in this sample should be larger by factor of 2 and it should use custom color of progress bar
https://staging.infragistics.com/webcomponents-demos/samples/inputs/circular-progress-indicator-styling

IG component in this sample should be smaller by factor of 2
https://staging.infragistics.com/webcomponents-demos/samples/inputs/circular-progress-indicator-dynamic

in other words, match size of circular-progress-indicator from other samples

**Comment by agoldenbaum** [comment]
Fixed with this PR: https://github.com/IgniteUI/igniteui-wc-examples/pull/435
