### ISSUE TITLE
Web Components Grid Overview main example superfluous code 

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-wc-examples#329]
In https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/overview#web-components-grid-example
The code is using some odd code with `ComponentRenderer` and `WebGridDescriptionModule` for some reason. 
```ts
    public get renderer(): ComponentRenderer {
        if (this._componentRenderer == null) {
            this._componentRenderer = new ComponentRenderer();
            var context = this._componentRenderer.context;
            WebGridDescriptionModule.register(context);
        }
        return this._componentRenderer;
    }
```
Not sure what those even are but I believe they are not needed (if anything they are confusing people just starting). @gmurray81 correct me if I'm wrong.

Perhaps those are from some generated output bit, but other samples on the same page don't have that

**Comment by gmurray81** [comment]
That's to load the metadata that the PropertyEditorPanel uses. If that sample isn't using the propertyEditorPanel it may be that "withDescriptions" should be removed from the modules array in the samples json

**Comment by gmurray81** [comment]
doesn't look like that sample uses the property editor panel, so just remove "withDescriptions" from the modules list in the json for that sample

**Comment by gmurray81** [comment]
to be more specific:

```json
"modules": [
    "withDescriptions",
    "grids/WebGridModule"
  ]
```

"withDescriptions" should only appear in this list in a sample json if the property editor panel is in use, in which case you should also see "layouts/PropertyEditorPanelModule". So any time you see "withDescriptions" without the panel being somewhere and that module being loaded, it should probably be removed.

**Comment by gmurray81** [comment]
we actually have some validation we run against the sample json to issue warnings in the editor, or duing the transform process. We should add this as something to warn/error about. I mean including that tag when you don't appear to be using the editor at all.
