### ISSUE TITLE
GeoMap sample does not show all geo-imagery tiles

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-wc-examples#365]
WC GeoMap sample does not have a combo box for changing geo-imagery tiles (Bing, ESRI, etc)
https://staging.infragistics.com/webcomponents-demos/samples/maps/geo-map-display-all-imagery

see this React sample for a reference 
https://staging.infragistics.com/react-demos/samples/maps/geo-map-display-all-imagery

**Comment by agoldenbaum** [comment]
Fixed with this PR: https://github.com/IgniteUI/igniteui-wc-examples/pull/435
