### ISSUE TITLE
Pivot Grid samples are missing

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-wc-examples#368]
![image](https://user-images.githubusercontent.com/44684385/214317522-baddbb2a-99f6-424a-98e8-d7ed09bd9899.png)

**Comment by HUSSAR-mtrela** [comment]
fixed on staging 
https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/pivot-grid/overview#web-components-pivot-grid-example
