### ISSUE TITLE
[IgcTree] - Loading on Demand freezes UI

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-wc-examples#459]
## Description  
Loading on Demand freezes UI

## Steps to reproduce  

1. Run sample
2. Expand Network
3. Click Computer notes (Documents, Music, Pictures, Reycle Bin) while Network is loading

You can repeat this process by clicking the refresh icon next to Network after its finished loading the child items. 

## Result  
Treemap locks up the UI

## Expected result  
Treemap does not lock up the UI

## Attachments  
https://codesandbox.io/s/exciting-hawking-7e3cmz

**Comment by ddaribo** [comment]
Hi @mddifilippo89,

The WC Tree LOD sample does not support such a large number of child nodes. As the LOD scenario is handled on application level, each data refresh involves removing the previously rendered child nodes, creating the new ones in the document and appending them. As DOM operations are quite time-consuming, I am afraid this behavior is expected given this implementation and the large number of child items in the fork of the sample.

Closing the current issue, as the default number of the loaded children is three, and a freeze is not reproduced in the topic [demo](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/tree#web-components-tree-load-on-demand). Should a sample with better performance be needed, a separate issue about creating such can be opened.
