### ISSUE TITLE
[Request for feature enhancement] - Infragistics tree

### ISSUE THREAD

**Issue by JinniaChathoth** [IgniteUI/igniteui-wc-examples#465]
Hi Team,

Currently we are facing issue with Infragistics tree component while loading large volume of data on demand (implementation is done in ReactJS), where the UI is getting frozen. 
An issue was raised on the same(https://github.com/IgniteUI/igniteui-wc-examples/issues/459), but it got closed.

Hence requesting for an enhancement in the Infragistics tree where it can support 1000 children under a node without UI freeze.

Adding the links for reference on the issue
[screenFreezeWhenMoreData.zip](https://github.com/IgniteUI/igniteui-wc-examples/files/11665201/screenFreezeWhenMoreData.zip)
https://codesandbox.io/s/great-bouman-73dfew?file=/src/LoadOnDemandData.ts

**Comment by rkaraivanov** [comment]
@teodosiah 

Can you create a new sample showing load on demand with large volume of data?
