### ISSUE TITLE
Grid : Checkboxes got uncheck

### ISSUE THREAD

**Issue by igDivya** [IgniteUI/igniteui-wc-examples#590]
1)Run any sample:
https://staging.infragistics.com/webcomponents-demos/samples/grids/grid/row-selection-template-numbers
https://staging.infragistics.com/webcomponents-demos/samples/grids/tree-grid/row-editing-style

2)Select multiple checkboxes
3)Click on any cell

Issue : Checkboxes got unchecked

**Comment by skrustev** [comment]
This is not a bug. That's how row selection works
