### ISSUE TITLE
Changing Sort Group In Data Aggregations Sample Does Nothing

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-wc-examples#645]
goto:
https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/charts/features/chart-data-aggregations

in sample set Initial Groups and Initial Summaries, then change Sort Groups
expect: columns are sorted by Sort group
actual: column order never changes

**Comment by mddifilippo89** [comment]
this has been fixed with Graham's fixes to the source and this PR
https://github.com/IgniteUI/igniteui-xplat-examples/pull/483

**Comment by mddifilippo89** [comment]
resolved
